sudo: required

language: java

services:
- docker

before_install:
- chmod +x gradlew

before_script:
- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

after_script:
- export DOCKER_REPO=pocketsquare/pocket-square-articles
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH | tr '/' '-' ; fi`
- docker build -t $DOCKER_REPO:travis-$TRAVIS_BUILD_NUMBER .
- docker tag $DOCKER_REPO:travis-$TRAVIS_BUILD_NUMBER $DOCKER_REPO:$TAG
- docker push $DOCKER_REPO

env:
  global:
  - secure: RRqJfE5JWYyv6JZOUYNmiXDndlxv4nmP7/p3VuSY0ZKV/QVR9hgJCkk+o/ayE8+NOnxHRLBGCPSDlby3pbK20RhvBKI108krTc0/xxGcIZFJA3w5bMMogikpO0eAA7815VZ2hk4kmDx+3NLoAMqov17ZSddxKNGSfPRuZ13272SN6n7cgH1xobfXR4ho3PjTkaTHHffrcZjn7tdzSD3pqTBnURtZG3ATkBzmYA/e/++nZjZYoTKltT4wmRF/h4CSEGhtiQwnr1mzUiQMvx/TMed2WnHMKah7lQIBZ9pVlFer8ZamGXXAEVydKNIZMyHKj7iEBy3zNWiK6fOpTPcUsn/AHZPx7ZpHr4B+dH85fbBY0zc+6ffRUOdSWckrja8y08d6no2DWvwQ60t4LxvPDrHIYxZraeBzauBhUJySVIa5Ee9unBBRVNB8V7G4HXQScJ5/nl3Qz4j+uYSDRvV0qHLyh+WMBZQaz3Gc5Vs1QQ/P0CKaBabnCa0VKSEXONDm1QAnakN3Sy0eKM/myRD848cgePL8TJLEBgRWLOtgkMVbysrwbgYmiCnOhjcEDgIPEiC7h9SHwtQSSxD35IW+HBKeevEutiG+yhRTZA9aBMWN8b6d0gzkopbVNBKQuJmfyjneAqaWuQQ8KnnWWtKZmfpLbdxLl2PTdQ/piplinGI=
  - secure: h0D7zwmalLqvD0HO8MvkxEgpkdXqldA4TFCD1/Ys3eIZeV7pdaD8FkfIibL4WEcIDVw4fG8sERd8DaDo2hx1wK9wlMFasaMvwbZ0x+eUNRJprhh/sQ0rVtMJFG41NVqNah0Twa6qqUSSTsIDYtVZoULq/o9NSqJb2l3NJBie8hif1h/IiYX5sEMNr14nAhb2G6x/DCAZMqo9CbE4Nylx77SIdm12a9z/sXReZt971LywCSFTOO9kb74Qgee3zVx4PKqld4cOrgVR/ZAOTI5ez4oiOF8L0/ASSVQD5EdC3/vq7nOf28Bb1jqdWdlhmzjt699xHahdgXetcC9uD8FqxyPNeTpvJOxuGOSjOPcwTpKZ1PAhiKa8sjsa2/osWnn6hmxpmqPk5I2iWDYXjTkM1R4jY7qc2cLdlMElovs9/aG6nEt4D5MmAlwScHhE27TlbZWxs8E4C//1H6qgbzT1tShNqnJSYTUUbZT2W6Qx58Edh7GL4R/RjuqiTAa3a0vsyq+WxJEerudl3jukcVXoOHlWHwXgZEPZGU/FmVVvONrz4DRftTiUWYd+cLQXP9rfHHdoqTP5/cglw4RnyE1QZYkpl2aeR3VzsCdpuhv84k/LMY5lhjOAwS63vlBdFE+VH3WsDS3rxJRsYEp1PY1YBZycgeX99qHCdAaLTrVjN1k=
  - secure: pj7Oj7CwiOJLioVO+0Gl05tBi2VMqRlIPTFcuyDZ+3xkrJ7dQE9wrBDAQHo645RYkBMuaDB97iByvaZJsZX9vfYcqdnw38LS2UYJ/JPRoLF4B5dp148vwuJBTHj6H/gVZCkeSt4Um/LnJgW2rSRlu1Ah+e8ZrfzlP6hXms3K8/SaLl9TDLPYLd+e439UKVqOWDzKDcFNBOl2UOjuvQ/F/0OL03o6i8Sf+hhqEMWD7uFtXls47XAvs9xe1h1WHpW968FDnjLHVHZHIJXpgdcAy48RspPC/zqO7xe5XtHYLB/94gGLsfab/7QDY6m66dtuDJcBb8Jn8xdwxQhmm29/ezfMRXHS+Svtj5jYMcw2RfABsWY7eX7v2+xdBdQVTez1jLkPcmQdE6SeJowp9tAC3nPOHCQc42iAdx+KiuUEYFDjK5+TmVpgcUpkd3z+E/AXnT2V+csarOTzAFsTKGFSM0UkbSewvlxcOPc3bxyiEkEHdgYO0cH+CW15yBYAq7S3GjwDCBGWjkMfOl8FnCL0RjuwwvcAlao4yti2U35tk9/Mtvw8brWcGQYkFWhuRrIKZNtWXh0vSrAVPXgqEGIWdBRHKy/aYEz694c8lq+gRHN8sHQZz6myBdIy3er1klm1II51nWIIW/rJ1VBO4WeJrtrUDyDRzc2OaltYViB9LFs=
