sudo: required

language: java

services:
- docker

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"

before_install:
- chmod +x gradlew

before_script:
- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

after_script:
- export DOCKER_REPO=pocketsquare/pocket-square-articles
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH | tr '/' '-' ; fi`
- docker build -t $DOCKER_REPO:travis-$TRAVIS_BUILD_NUMBER .
- docker tag $DOCKER_REPO:travis-$TRAVIS_BUILD_NUMBER $DOCKER_REPO:$TAG
- docker push $DOCKER_REPO

env:
  global:
  - secure: pnKgn2/Basee644RSHCGUK9nHuZvX7m3d/rKuVhVgQ9uliwxH9E+my5MfwjTekYy7esm3dgzlxWe75Lztc4IOP1F6VMRfQzFxOZRhyhdF74wDWWpdWYAODnlnW64fWB6DpqpurgFmOvgD2Npo4W3fnEkXLDsEI2CFpxnxKnS9/2G6t92E8Q1MIfVxQTAoeZe0jyUlECLTvkEmWEZLNCjpZgRKQ2lPLxfeCW3YhmFklFpdgV0yYkbSTIuz7sgUj2yc1ibiHBW9WPVS+evNLXVE2epH5fw9N+PrpOi94A/TFuEu+6uQgUzOYZHABlNvYnTFUCQPcvAyhWv8ZPQoR2SV2QURAwa2mFE4eHJN4zixFWIeuetz/uHHgVjDrT66hSfRYewdsSshIAOqSQQfpQu04mXgYuCpJ/v8mUVQCIIJi9tQQ4SMG7hS2fc3NRVNwKsjNymu0nhGYQhf3nt69AiT7CN7SKJFNPFEsipnKNe4VtKdOk1WaMjGKv4/JH1KAcK4t+bWd2FOVNHZxmLis1Mt7AQp7zGfLA62XRpThMWfxtxhHZU0jk/+zL82muX5eyPZHbtsP3zuqU0jTxU2ralspWYeBuMwkcU9K8KePk29Rm3c40S/YQfx6/amnQ3kJorbnDls5922c49F4j8vGMgNHQ9AqKO7D5O6wE5A/0eKLM=
  - secure: gFsPtsHXUz71jNY91eC9B/jvTf5+6kAAEMRXWwmbYv609EawltlssrmvWpQAYtOyOkDIlxrUmvVnczw29x+ng0STCiZLe9JfO8T8ycc/iMKEDnxumvcte+DtGBI5Ig9uAF8ayEH0awlA5zL+J5qrCzF9k4FF8VrZZmRhD1wu3mxCSY4vv3UfWSqqwMBGuq/CUW7Q9rEDr0Y1lvoiSqmgWLdjKFj1zssHjLipidk1rPnPNm/vud0tYc+SYifw2iLelzgYBubZ30JZf4somSbJneJyERmBXRowIP4+c4Zco7O8Uw4qPb/Nj5ikJwaUr3GncXwP4dwYBHmChpxsEb4tbKCuVD8UkbkyegWYZcun5GXM75jnQ7XATzedyb4mBnPSUMiVlko1Dg84fZMNBp08Eocq8G0qa6jmhK3O3QK553c2NLX1XQp6afT1BXbsFe/0n+cjeCBZOSQ745B89gfCrj+l4uxQOZV5Fhxocb/3OoQmAsAgGznfikZarIh/V64OZlhViHMDyftfzahuAM1SD61Wd721iUKhefGhvI+xYZzePBe2fOqU1oMLZhHvut24WDj9nd64plE5JSL6nW3ApbDWvwbu+Gho20SDah9FA1zJRMakhOgs00lJJcbN8P1fF/azMyCy/Bp33gfOsPNz8LnehNXvVOU9zBBkebX7uz0=
  - secure: D4kJTnY+WZ/UnH+T2PJA0d1NGqhLSPChGqQh9etuu/90sCvH26CssT4siyfVpwKiDc0d7myLX3V1DaRyZ9FIMylWY8jQSh9CYR5mUd0fOT9JNPo7YxdE5FgNapxl0k2ClAuCWIy7tLpcevJTDuLd8JXy+K5PhAd7HYOAlq3NlfEQS/BkmO8T8SwRcdgVnV6J1Z1znTpm3iCgKGSQGFGJ0Pe/Rw253ODj2a3GAl+Ynu4GP/Iv6QXQ8qedfzzA2VWDphAV3Ifw4SChXRHhuddmicfkPRVsAhwP0vr3uVuCiifhumidY2Vh9OqIO3wwgapa8hoZn4rKrwRGfB2cim4mxWzEPXb1NR1plvG2EKQVr6akp2+QgplYJEp4gdVM1K731zq8QqLDzgunxO16kLq8Ny7Yw+zc7PRxYY7MIurH3eBpo8UzW1mabvslpU5On54mgQGLq+DZ9VxYbIkfYwmG9V35TQXPtWqRMhyJvy7XofTe6Xuf9w3gVwcX4K7kGUlbdFZBCCcI9geIbeeIzjNA4jJDU2y6uXqXzi7ZgQpAyxrrD/8MJvTTUToryY6YbcZ6wXWi0w62dOS5UH8R3iLP7wR2jooUyQA0PJ5XjLZeBKi6rvhInbSvMFEaHXHhcnh4KBsJKjLcoVONDSlktv0peEt+UOVbEu2AVtTFTOIr58Y=
